spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret-key: ${JWT_SECRET}
  access-expire: 24h
  refresh-expire: 1h

Ai:
  request-url: ${AI_SERVER}
